# Generated by Django 5.2.7 on 2025-11-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_book_image_alter_book_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
